### PR TITLE
Sort steps by timestamps

### LINKED ISSUE #1367: Pipelineruns in Tekton dashboard show incorrect status for each step
# Expected behavior
When running a pipelinerun in Tekton dashboard,  the status for each step run in the pipelinerun should report correctly 

# Actual behavior
Tekton dashboard does not report status for the steps in a pipelinerun correctly

For example, in Kabanero 0.9.0-rc.2, run pipeline nodejs-express-build-deploy-pl in Tekton dashboard. It failed at step `image-digest-exporter-pndfj` and other steps showed as `Not run` as following

image

But I looked into each step, I see that it successfully ran steps `enforce-stack-policy-pre-build`, `build`, `enforce-stack-policy-post-build`, and failed on` push` step.
So the steps that ran successfully should show as `Completed` and the push step should show as `Failed` and the rest of the steps should be `Not run`

The followings are the screenshots for the steps that ran successfully, but they showed as `Not run`

image

image

image

- The `push` step is actually failed with error,  but it showed as `Not run` instead of Failed

image

# Steps to reproduce the problem

1. Create a webhook for nodejs express app with pipeline nodejs-express-build-deploy-pl from the Tekton dashboard.  Use OpenShift internal registry (e.g. _image-registry.openshift-image-registry.svc:5000/svt-project2_)
2. Make a small change in the app git repo to trigger the pipelinerun.

# Environment
- Kubernetes Platform: OPC 4.4.3

- Tekton Pipelines version:   tekton.version: v0.11.3

- Tekton Triggers version:

- Tekton Dashboard version:

Image ID:       gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard@sha256:3b4dc45de5ae0e741099018afe3e1108cb93f70aa24138456be03d9fde677269

# Additional Info

This problem was found when pushing the image to internal registry and it failed with error 500
```
error pushing image "image-registry.openshift-image-registry.svc:5000/svt-project2/radcl-njsexpress-app:3d38ec4eea3c14cd93e68771319804f7fea86035" to "docker://image-registry.openshift-image-registry.svc:5000/svt-project2/radcl-njsexpress-app:3d38ec4eea3c14cd93e68771319804f7fea86035": error copying layers and metadata from "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.imagestore=/var/lib/shared,overlay.mount_program=/usr/bin/fuse-overlayfs,overlay.mountopt=nodev,metacopy=on]image-registry.openshift-image-registry.svc:5000/svt-project2/radcl-njsexpress-app:3d38ec4eea3c14cd93e68771319804f7fea86035" to "docker://image-registry.openshift-image-registry.svc:5000/svt-project2/radcl-njsexpress-app:3d38ec4eea3c14cd93e68771319804f7fea86035": Error writing manifest: Error uploading manifest 3d38ec4eea3c14cd93e68771319804f7fea86035 to image-registry.openshift-image-registry.svc:5000/svt-project2/radcl-njsexpress-app: received unexpected HTTP status: 500 Internal Server Error
```

### PR DESCRIPTION
**Pull request by JustinKuli**
# Changes

Sort steps by timestamps in a TaskRun

Currently, all injected steps appear before the regularly defined steps in some views. Now they are sorted by the finishedAt timestamp in each step's status, with ties broken by the startedAt timestamp.

The current order is not always correct, since some injected steps actually run after regular steps. This ordering also causes some steps to be incorrectly labelled as either skipped or failed.

The new order should be better, but it will still depend on the precision of the timestamps: seconds might not be sufficient in all cases. There are plans in 'pipeline' to increase the precision.

Fixes #1367

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by JustinKuli** [comment]
Original problem: the "image-digest-exporter" step ( which is injected by a git PipelineResource) is incorrectly identified as the failed step.

Actually, the "push" step is the failing one, as the "image-digest-exporter" was skipped. We can see the correct output after we sort by the timestamps.

I just want to note that sorting them by the timestamps isn't a perfect solution. The "image-digest-exporter" step should happen after the "push" step, like we see above. But when multiple steps are skipped, the start and finish times might be equal, and it leads to slightly incorrect results.

## Current state (example where push fails):
1367-current-1

## After this change (example where push fails):
1367-adjusted-1

## Imperfect ordering even after this change:
1367-adjusted-2

**Comment by AlanGreene** [comment]
@JustinKuli can you share some of the Pipelines / Tasks you used to test this? I don't think I'm seeing any difference testing this out locally. The `image-digest-exporter` step is still showing before the failed step, and the failed step is showing as not run as a result. This could be down to the lack of precision in the times as you mentioned.

**Comment by JustinKuli** [comment]
@AlanGreene I was just using the pipeline / tasks from https://developer.ibm.com/tutorials/tekton-triggers-101/, since that was something I already had in my cluster. The Tasks and Pipeline are here: https://github.com/ncskier/catapp/blob/master/tekton/build-and-deploy-openshift-pipeline.yaml

In your Task, do you have another "normal" step before the failing one (which would complete well before the `image-digest-exporter` step)? Because in the current implementation, the image-digest-exporter step will always come first... regardless of if there was another step that finished even earlier (the "build" step in my example runs).

Let me put together a more repeatable Task that can demonstrate this. I might have just gotten lucky in my run.

**Comment by JustinKuli** [comment]
@AlanGreene here's a simple example which seems to give repeatable results for me (I ran it five times, all with the same result):
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: fail-bbb-skip-image-
spec:
  resources:
    outputs:
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: fake-registry.io/fake-image
  taskSpec:
    resources:
      outputs:
      - name: image
        type: image
    steps:
    - name: aaa
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        sleep 3
        echo "Step aaa will complete successfully..."
        sleep 3
    - name: bbb
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        sleep 3
        echo "Step bbb will fail..."
        sleep 3
        exit 1
```

## Viewed using the current dashboard:
tekton-1367-new-1

## Viewed using my build:
tekton-1367-new-2

File: packages/utils/src/utils/index.js [hunk 1]
```diff
@@ -182,13 +182,38 @@ export function formatLabels(labelsRaw) {
...
+      return 0;
+    }
+    if (iFinishedAt !== jFinishedAt) {
+      return iFinishedAt - jFinishedAt;
+    }
+    // if finishedAt timestamps are equal, compare the startedAt timestamps
+    if (!iStartedAt || !jStartedAt) {
+      return 0;
+    }
+    if (iStartedAt !== jStartedAt) {
```
Comment (AlanGreene) [inline packages/utils/src/utils/index.js:203]: should be able to `return iStartedAt - jStartedAt;` here and avoid the additional `if` and `return 0`

**Comment by JustinKuli** [comment]
@AlanGreene Review comments implemented, commits squashed, and rebased to master.
