### PR TITLE
Fix error showing TaskRun steps that have not run

### LINKED ISSUE #644: If the build step in tekton pipeline fails, tekton dashboard shows the push step as green
# Expected Behavior

- When the `build-bud` step in kabanero pipeline fails due to some reason, the `build-push` step never runs from kabanero pipelines perspective.
And same should be seen on the Tekton-Dashboard with red mark for `build-bud` step and `build-push` step.

# Actual Behavior

- When the `build-bud` step is failing the the pipelinerun, still the Tekton-Dashboard is showing that `build-push` step succeeded.

# Steps to Reproduce the Problem

1.  Create a webhook for java-microprofile project from the tekton dashboard.
2. Make some code changes with compile time errors , so the `build-bud` step fails.

# Additional Info

   From Kabanero pipelines perspective we created webhook for java-microprofile project in my github.ibm.com from the tekton dashboard.
    I made some code changes with compile time errors , so the `build-bud` step fails.

Results:

    

- As the pipelinerun failed, the tekton dashboard shows below screenshot.

Screen Shot 2019-10-15 at 1 05 31 PM

-  However when we investigated from the oc logs command we found below results

- Logs Snippet for build-bud container in the pod (which was as expected to build fail):-

`oc logs -f my-java-mp-webhook-1571152644-build-task-wndcp-pod-2f0e7d -c step-build-bud`
```
Downloaded from central: https://repo.maven.apache.org/maven2/com/google/collections/google-collections/1.0/google-collections-1.0.jar (640 kB at 1.2 MB/s)
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /project/user-app/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /project/user-app/src/main/java/dev/appsody/starter/StarterApplication.java:[8,5] <identifier> expected
[ERROR] /project/user-app/src/main/java/dev/appsody/starter/StarterApplication.java:[9,2] reached end of file while parsing
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  57.022 s
[INFO] Finished at: 2019-10-15T15:27:33Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project starter-app: Compilation failure: Compilation failure: 
[ERROR] /project/user-app/src/main/java/dev/appsody/starter/StarterApplication.java:[8,5] <identifier> expected
[ERROR] /project/user-app/src/main/java/dev/appsody/starter/StarterApplication.java:[9,2] reached end of file while parsing
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
subprocess exited with status 1
subprocess exited with status 1
error building at STEP "RUN mvn install -DskipTests": exit status 1
```

- When we checked the `build-push` container logs

`oc logs -f my-java-mp-webhook-1571152644-build-task-wndcp-pod-2f0e7d -c step-build-push`

Logs never returned anything which means the `build-push` step never ran since earlier step failed. :
```
[root@crofts1 common]# oc logs -f my-java-mp-webhook-1571152644-build-task-wndcp-pod-2f0e7d -c step-build-push
[root@crofts1 common]# 
```

### PR DESCRIPTION
**Pull request by ncskier**
# Changes

Fixes #644
This fix shows a neutral "Not run" status for steps that follow a step with an
error. Previously, these steps showed a misleading green "Completed" status.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by ncskier** [comment]
Thanks for the feedback @AlanGreene! I'll update this PR to show the default step state instead of hiding the steps 👍 
/hold

File: packages/components/src/components/Log/Log.js [hunk 1]
```diff
@@ -82,6 +82,11 @@ export class LogContainer extends Component {
           id: 'dashboard.pipelineRun.stepFailed',
           defaultMessage: 'Step failed'
         });
+      case 'Not run':
```
Comment (AlanGreene) [inline packages/components/src/components/Log/Log.js]: no need to display a trailer on the logs for this case

File: packages/components/src/components/PipelineRun/PipelineRun.js [hunk 2]
```diff
@@ -27,6 +27,7 @@ import {
 } from '@tektoncd/dashboard-utils';
 
 import { Log, RunHeader, StepDetails, TaskTree } from '..';
+import { updateUnexecutedSteps } from '../../../../../src/utils';
```
Comment (AlanGreene) [inline packages/components/src/components/PipelineRun/PipelineRun.js]: code in packages/* cannot consume code directly from the core dashboard, it must be available in a published npm package (in this case it may make sense to move it to packages/utils) otherwise it will not work for 3rd parties consuming the @tektoncd/dashboard-components package.

File: packages/components/src/components/Task/Task.js [hunk 3]
```diff
@@ -89,24 +91,28 @@ class Task extends Component {
...
+                  reason === 'TaskRunCancelled' && status !== 'terminated'
+                    ? 'cancelled'
+                    : status;
+                return (
+                  <Step
+                    id={id}
+                    key={id}
+                    onSelect={this.handleStepSelected}
+                    reason={stepReason}
+                    // reason={index > errorIndex ? '' : stepReason}
```
Comment (AlanGreene) [inline packages/components/src/components/Task/Task.js]: remove

File: src/utils/index.js [hunk 4]
```diff
@@ -74,3 +74,36 @@ export function getGitValues(url) {
 
   return { gitServer, gitOrg, gitRepo: `${gitRepo}.git` };
 }
+
+// Update the status of steps that follow a step with an error
+export function updateUnexecutedSteps(steps) {
+  if (typeof steps === 'undefined') {
```
Comment (AlanGreene) [inline src/utils/index.js]: is there any change `steps` could be null? if so might be safer just to check `if (!steps) {`

File: src/utils/index.js [hunk 5]
```diff
@@ -74,3 +74,36 @@ export function getGitValues(url) {
...
+    return steps;
+  }
+  let errorIndex = steps.length - 1;
+  return steps.map((step, index) => {
```
Comment (AlanGreene) [inline src/utils/index.js]: I think it's worth raising https://github.com/tektoncd/pipeline/issues/1439 in the next working group meeting at least to ask for feedback on the issue.

It also looks like the behaviour when cancelling a PipelineRun is different, I see steps marked as Waiting instead of Completed.

Having this workaround in the dashboard for now resolves the immediate user-facing issue for users of the dashboard, but users of kubectl or other tools still have the same misleading information presented (i.e. a step that hasn't executed is marked as Completed), and each tool needs to handle this themselves.

**Comment by AlanGreene** [comment]
@ncskier can you also update the PR title + description to reflect the change in approach taken here? Thanks

File: packages/components/src/components/PipelineRun/PipelineRun.js (hunk 2 above)
Comment (ncskier) [reply packages/components/src/components/PipelineRun/PipelineRun.js]: @AlanGreene So, what would be the best way for me to make this function available? It's used in the following files:
- `src/containers/TaskRun/TaskRun.js`
- `packages/components/src/components/Task/Task.js`
- `packages/components/src/components/PipelineRun/PipelineRun.js`

If I move the function declaration to `packages/utils`, then can I import it from `src/containers/TaskRun/TaskRun.js`?

Comment (AlanGreene) [reply packages/components/src/components/PipelineRun/PipelineRun.js]: yes that'll work 👍 
you'll just need to import it from `@tektoncd/dashboard-utils` rather than by local path

File: packages/components/src/components/Log/Log.js (hunk 1 above)
Comment (ncskier) [reply packages/components/src/components/Log/Log.js]: True, it's not really necessary. I'll remove it 👍

File: src/utils/index.js (hunk 4 above)
Comment (ncskier) [reply src/utils/index.js]: Ok, thanks. I changed it. 

How about for these lines (https://github.com/tektoncd/dashboard/pull/653/files#diff-44384c8c75c7b5aab1477fe8f0736133R162-R163):
```
typeof step.stepStatus !== 'undefined' &&
typeof step.stepStatus.terminated !== 'undefined'
```
@AlanGreene Is it safer to do `if (!step.stepStatus && step.stepStatus.terminated)...` ?

Comment (AlanGreene) [reply src/utils/index.js]: `if (step.stepStatus && step.stepStatus.terminated) {`

yes, easier to read / reason about too (IMO)

Comment (ncskier) [reply src/utils/index.js]: Ok, thanks! 👍

**Comment by ncskier** [comment]
Thanks for the feedback @AlanGreene! I've updated the PR title & description, and I think I've addressed all of your concerns. Let me know if there's anything else that I can do 🙂

File: packages/components/src/components/PipelineRun/PipelineRun.js [hunk 6]
```diff
@@ -27,6 +27,7 @@ import {
 } from '@tektoncd/dashboard-utils';
 
 import { Log, RunHeader, StepDetails, TaskTree } from '..';
+import { updateUnexecutedSteps } from '../../../../utils';
```
Comment (AlanGreene) [inline packages/components/src/components/PipelineRun/PipelineRun.js]: import from '@tektoncd/dashboard-utils'

File: packages/components/src/components/Task/Task.js [hunk 7]
```diff
@@ -17,6 +17,8 @@ import ChevronRight from '@carbon/icons-react/lib/chevron--right/16';
 import CloseFilled from '@carbon/icons-react/lib/close--filled/16';
 import { Spinner, Step } from '@tektoncd/dashboard-components';
 
+import { updateUnexecutedSteps } from '../../../../utils';
```
Comment (AlanGreene) [inline packages/components/src/components/Task/Task.js]: import from '@tektoncd/dashboard-utils'

**Comment by ncskier** [comment]
Ah, thanks @AlanGreene! Just fixed the imports 😁
