### PR TITLE
Fix error where selecting x on namespace button breaks page

### LINKED ISSUE #1132: Selecting `x` in the namespace box breaks secrets page
# Expected behavior
On create secret I tpyed in a namespace that didnt exist and clicked create 
When tried to press the x in the namespace box it broke and came up with error 
`Error loading page Cannot read property 'text' of null`

Inspector error is:
`ErrorBoundary.js?9c7c:68 ErrorBoundary Object
componentDidCatch @ ErrorBoundary.js?9c7c:68`

# Actual behavior

# Steps to reproduce the problem

1. Try create secret 
2. Put in a namespace doesnt exist
3. press submit 
4. press x on namespace to delete namespace 

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info

### PR DESCRIPTION
**Pull request by CarolynMabbott**
# Changes
Fixes #1132 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

File: src/containers/CreateSecret/CreateSecret.js [hunk 1]
```diff
@@ -91,16 +91,24 @@ export /* istanbul ignore next */ class CreateSecret extends Component {
...
+        }
+        return { [stateVar]: stateValue, invalidFields: newInvalidFields };
+      });
+    } else {
+      const stateValue = '';
+      this.setState(prevState => {
+        const newInvalidFields = prevState.invalidFields;
+        return { [stateVar]: stateValue, invalidFields: newInvalidFields };
+      });
+    }
```
Comment (AlanGreene) [inline src/containers/CreateSecret/CreateSecret.js]: We could simplify this a lot if we mark the namespace as invalid when it's cleared. This would give earlier feedback to the user instead of letting them clear it only to show an error later when they try to submit the form.

```diff
diff --git a/src/containers/CreateSecret/CreateSecret.js b/src/containers/CreateSecret/CreateSecret.js
index 637716a..eaff6ca 100644
--- a/src/containers/CreateSecret/CreateSecret.js
+++ b/src/containers/CreateSecret/CreateSecret.js
@@ -91,7 +91,7 @@ export /* istanbul ignore next */ class CreateSecret extends Component {

   handleChangeNamespace = e => {
     const stateVar = 'namespace';
-    const stateValue = e.selectedItem.text;
+    const stateValue = e.selectedItem ? e.selectedItem.text : '';
     this.setState(prevState => {
       const newInvalidFields = prevState.invalidFields;
       if (validateInputs(stateValue, stateVar)) {
```

Comment (CarolynMabbott) [reply src/containers/CreateSecret/CreateSecret.js]: If a user presses the `X` button to clear the namespace surely they would be doing this to select another namespace anyway

Comment (CarolynMabbott) [reply src/containers/CreateSecret/CreateSecret.js]: Have done this 😸
